# Generated by Django 5.0.14 on 2026-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('numero_camiseta', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
