# Generated by Django 5.0.14 on 2026-09-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoresapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero_camiseta',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18), ('edad__lte', 40)), name='edad_jugador_entre_18_y_40'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.CheckConstraint(check=models.Q(('numero_camiseta__gte', 1), ('numero_camiseta__lte', 99)), name='numero_camiseta_entre_1_y_99'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido'), name='nombre_apellido_unico'),
        ),
    ]
