# Generated by Django 5.0.14 on 2026-09-24 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoresapp', '0002_alter_jugador_numero_camiseta_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jugador',
            name='edad_jugador_entre_18_y_40',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
