# Generated by Django 4.2.27 on 2026-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoresapp', '0003_remove_jugador_edad_jugador_entre_18_y_40_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Arquero', 'Arquero'), ('Defensa', 'Defensa'), ('Mediocampista', 'Mediocampista'), ('Delantero', 'Delantero')], max_length=20),
        ),
    ]
